modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="power_armor_mod"
version="${file.jarVersion}"
displayName="Armorpunk"
logoFile="power_armor_mod.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Jetug" #optional
description='''
This mod adds mechanical armor
'''

[[dependencies.power_armor_mod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.power_armor_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
