modLoader="javafml"
loaderVersion="[40,)"
license="The MIT License"
[[mods]]
modId="chassis_core"
version="${file.jarVersion}"
displayName="Chassis core"
logoFile="chassis_core.png"
authors="Jetug"
description='''Core for exoskeleton armor mods'''

[[dependencies.chassis_core]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.chassis_core]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.chassis_core]]
    modId="azurelib"
    mandatory=true
    versionRange="[1.0.23,)"
    ordering="AFTER"
    side="BOTH"